<a href="https://colab.research.google.com/github/Durwankur/R-Lab/blob/main/Experiment4_writeup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**R Programming apply family of functions**

In this experiment we will learn about how to use apply family of functions
to do data wrangling and avaoid use of looping constructs 

The R base manual tells you that it’s called as follows: 

```
apply(X, MARGIN, FUN, ...)
```


```X``` is an array or a matrix if the dimension of the array is ```2```

```MARGIN``` is a variable defining how the function is applied: 
 

*   When ```MARGIN=1```, it applies over rows 
*   Whereas with ```MARGIN=2```, it works over columns
*   ```MARGIN=c(1,2)```, it applies to both rows and columns;     

and
```FUN```, represents the function that you want to apply to the data. It can be any R function, including a User Defined Function (UDF).

In [9]:
# Complete the following code by using apropriate apply family function
# Construct a 5x6 matrix
X <-matrix(rnorm(30), nrow=5, ncol=6)
X
# Sum the values of each column with apply()
X_col <- apply(X,2,sum)
X_col
# Sum the values of each row with apply()
X_rowsum <- apply(X,1,sum)
X_rowsum

[,1]       [,2]        [,3]       [,4]       [,5]       [,6]      
[1,] -0.7117205  0.62796106  0.1173359  0.3813413 -0.3915945 -0.1409635
[2,]  1.4014731  0.10641974  0.1755353 -0.4445041  0.0756899  1.5453217
[3,] -1.0963462 -0.05566686 -1.3910361 -0.2591903  0.7083384  0.5717319
[4,]  0.9465556 -0.33342436 -1.4581448  0.7395851 -1.5670553  2.8348193
[5,]  0.6767235 -1.39552474  1.0589345 -1.1474793  0.6963375  1.0296537

[1]  1.2166856 -1.0502352 -1.4973752 -0.7302472 -0.4782841  5.8405631

[1] -0.1176402  2.8599356 -1.5221692  1.1623356  0.9186451

In [10]:
# Complete the following code by using looping construct
# Construct a 5x6 matrix
X <-matrix(rnorm(30), nrow=5, ncol=6)
X
# Sum the values of each column with apply()
X_col1 <- apply(X,2,sum)
X_col1


[,1]       [,2]        [,3]       [,4]       [,5]       [,6]      
[1,]  0.8754408 -0.41090344 -0.1141708 -0.6754847 -0.6728623  0.5102504
[2,]  0.2041897 -0.50817958 -0.5774118  0.5071649  0.8605531  0.3858691
[3,]  0.5289479  0.04060057 -2.0580388  0.4428236  1.0539659  0.1135671
[4,] -0.3821145 -0.11191697 -1.1739080 -0.2381204  1.3305530  0.9177215
[5,]  0.4744400 -0.01745028 -0.6855903  0.4369313 -0.7392426 -1.6280011

[1]  1.7009038 -1.0078497 -4.6091196  0.4733146  1.8329671  0.2994071

The **lapply()** Function is used when You want to apply a given function to every element of a list and obtain a list as a result.
 
 Syntax of **lapply()** looks like the **apply()** function.

There is a slight difference in way they work, which is :



1.   **lapply()** can be used for other objects like dataframes, lists or vectors
2.   The output returned by **lapply()** is a list (which explains the “l” in the function name), which has the same number of elements as the object passed to it.

To see how this works, complete the following code block.

**lapply()** is a quite common operation performed on real data when making comparisons or aggregations from different dataframes.


In [11]:
# Using sequence 1:9 create a matrix A with size 3*3
A <- matrix(1:9, nrow=3, ncol=3)
A

#Using sequence 4:15 create a matrix B with size 4*3
B <- matrix(4:15, nrow=4, ncol=3)
B

#Using sequnce 8:10 create a matrix C with size 3*2
C <- matrix(8:10, nrow=3, ncol=2)
C

# create variable MyList as list of matrix A, B, C
MyList <- list(A, B, C)
MyList




[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 4     8   12  
[2,] 5     9   13  
[3,] 6    10   14  
[4,] 7    11   15

[,1] [,2]
[1,]  8    8  
[2,]  9    9  
[3,] 10   10

[[1]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[2]]
     [,1] [,2] [,3]
[1,]    4    8   12
[2,]    5    9   13
[3,]    6   10   14
[4,]    7   11   15

[[3]]
     [,1] [,2]
[1,]    8    8
[2,]    9    9
[3,]   10   10

In [12]:
# Using lapply and [ operator Extract the 2nd column from `MyList` with the selection operator `[` with `lapply()`
lapply(MyList, '[', , 2)

# Using lapply and [ operator Extract the 4th row from `MyList` with the selection operator `[` with `lapply()`
lapply(MyList, '[', 4, )
#Error because matrix A and C have 3 rows.

[[1]]
[1] 4 5 6

[[2]]
[1]  8  9 10 11

[[3]]
[1]  8  9 10

ERROR: ignored

In [ ]:
# Using lapply and [ operator Extract the 1st row from `MyList` with the selection operator `[` with `lapply()`
lapply(MyList, '[', 1, )

The **sapply()** Function

The **sapply()** function works like **lapply()**, but it tries to simplify the output to the most elementary data structure that is possible. And indeed, ```sapply()``` is a **‘wrapper’** function for **lapply()**.

Let’s repeat the extraction operation of a single element as in the last example, but now take the first element of the second row (indexes 2 and 1) for each matrix.

Applying the **lapply()** function would give us a list unless you pass ```simplify=FALSE``` as a parameter to **sapply()**. Then, a list will be returned. See how it works in the code chunk below:



In [ ]:
# Return a list with `lapply()`
lapply(MyList,"[", 2, 1 )

# Return a vector with `sapply()`
sapply(MyList,"[", 2, 1 )

# Return a list with `sapply()`
sapply(MyList,"[", 2, 1, simplify=F)

# Return a vector with `unlist()`
unlist(lapply(MyList,"[", 2, 1 ))

In this Text Block Write note on mapply function and give exampe code and exaplain use of mapply function.

Ans:
mapply can be used to call a function FUN over vectors or lists one index at a time. In other words the function is first called over elements at index 1 of all vectors or list, its then called over all elements at index 2 and so on.  


In [ ]:
# Example use of mapply function
mapply(rep, 1:5, 5:1)
#This passes the sequence 1:4 to the first argument of rep() and the sequence 4:1 to the second argument.

 Example: 
 It takes in two parameters x and y. The values of x come from the second argument (x=c(2,3)) and the values of y come from the 3rd argument (y=c(3,4)). x and y both have two values so the function is called twice. The first time its called with the first values of x and y (x=2 and y =3 which gives 8). The second time its called with the second values of x and y (x=3 and y=4 which gives 81)

In [ ]:
 mapply(function(x,y){x^y},x=c(2,3),y=c(3,4))
